LaMiaPizzeriaConCategoriaEOrdini/Models/Pizza.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace LaMiaPizzeriaConCategoriaEOrdini.Models
{
    public class Pizza
    {

        //MODELLO PIZZA

        //Proprietà Pizza
        public int Id { get; set; }

        [Column(TypeName = "varchar(300)")]
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [StringLength(300, ErrorMessage = "Non puoi andare oltre i 300 caratteri")]
        public string Image { get; set; }

        [Column(TypeName = "varchar(30)")]
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [StringLength(300, ErrorMessage = "Non puoi andare oltre i 100 caratteri")]
        public string Name { get; set; }

        [Column(TypeName = "text")]
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        public string Description { get; set; }

        [Column(TypeName = "float(2)")]
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        public float Price { get; set; }


        public int? CategoryId { get; set; }
        public Category? Category { get; set; }

		public Order? Order { get; set; }

		//Costruttore pizza vuoto utile per quanto si lavora con DB
		public Pizza()
        {

        }

        //Costruttore Pizza senza id perché gestito da DB
        public Pizza(string image, string name, string description, float price)
        {
            Image = image;
            Name = name;
            Description = description;
            Price = price;
        }

    }
}

LaMiaPizzeriaConCategoriaEOrdini/Controllers/OrderController.cs
using LaMiaPizzeriaConCategoriaEOrdini.Database;
using LaMiaPizzeriaConCategoriaEOrdini.Models;
using Microsoft.AspNetCore.Mvc;

namespace LaMiaPizzeriaConCategoriaEOrdini.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            using (PizzaContext db = new PizzaContext())
            {
                List<Order> listOrders = db.Orders.ToList<Order>();
                return View("Index", listOrders);
            }
        }

        // METODO GET
        [HttpGet]
        public IActionResult Create()
        {
            using (PizzaContext db = new PizzaContext())
            {
                List<Pizza> pizzasFromDb = db.Pizzas.ToList<Pizza>();

                PizzaOrdersView modelForView = new PizzaOrdersView();
                modelForView.Pizzas = pizzasFromDb;

                return View("Create", modelForView);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Order formData)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", formData);
            }

            using (PizzaContext db = new PizzaContext())
            {
                db.Orders.Add(formData);
                db.SaveChanges();
            }

            return RedirectToAction("Index", "Home");

        }
    }
}

LaMiaPizzeriaConCategoriaEOrdini/Controllers/PizzaController.cs
using LaMiaPizzeriaConCategoriaEOrdini.Database;
using LaMiaPizzeriaConCategoriaEOrdini.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LaMiaPizzeriaConCategoriaEOrdini.Controllers
{
    public class PizzaController : Controller
    {
        public IActionResult Index()
        {
            using (PizzaContext db = new PizzaContext())
            {
                List<Pizza> listPizzas = db.Pizzas.ToList<Pizza>();
                return View("Index", listPizzas);
            }
        }

        public IActionResult Details(int id)
        {
            using (PizzaContext db = new PizzaContext())
            {
                //Con include gli dico di non usare il lazy coding e di prendermi anche l'oggetto category.
                Pizza pizzaFound = db.Pizzas
                    .Where(PizzaNelDb => PizzaNelDb.Id == id)
                    .Include(pizza => pizza.Category)
                    .FirstOrDefault();

                if (pizzaFound != null)
                {
                    return View(pizzaFound);
                }


                return NotFound("La pizza non esiste!");
            }


        }

        // METODO GET
        [HttpGet]
        public IActionResult Create()
        {
            using (PizzaContext db = new PizzaContext())
            {
                List<Category> categoriesFromDb = db.Categories.ToList<Category>();

                PizzaCategoriesView modelForView = new PizzaCategoriesView();
                modelForView.Categories = categoriesFromDb;

                return View("Create", modelForView);
            }

        }


        // METODO POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PizzaCategoriesView formData)
        {
            if (!ModelState.IsValid)
            {
                using (PizzaContext db = new PizzaContext())
                {
                    List<Category> categories = db.Categories.ToList<Category>();
                    formData.Categories = categories;
                }
                return View("Create", formData);
            }

            using (PizzaContext db = new PizzaContext())
            {
                db.Pizzas.Add(formData.Pizza);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        // METODO PUT (GET + POST)

        [HttpGet]
        public IActionResult Update(int id)
        {
            using (PizzaContext db = new PizzaContext())
            {
                Pizza pizzaToModify = db.Pizzas.Where(pizza => pizza.Id == id).FirstOrDefault();

                if (pizzaToModify == null)
                {
                    return NotFound("La pizza non è stata trovata");
                }

                List<Category> categories = db.Categories.ToList<Category>();

                PizzaCategoriesView modelForView = new PizzaCategoriesView();
                modelForView.Pizza = pizzaToModify;
                modelForView.Categories = categories;

                return View("Update", modelForView);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, PizzaCategoriesView formData)
        {
            if (!ModelState.IsValid)
            {
                using (PizzaContext db = new PizzaContext())
                {
                    List<Category> categories = db.Categories.ToList<Category>();
                    formData.Categories = categories;
                }

                return View("Update", formData);
            }

            using (PizzaContext db = new PizzaContext())
            {
                Pizza pizzaToUpdate = db.Pizzas.Where(pizza => pizza.Id == id).FirstOrDefault();

                if (pizzaToUpdate != null)
                {
                    pizzaToUpdate.Image = formData.Pizza.Image;
                    pizzaToUpdate.Name = formData.Pizza.Name;
                    pizzaToUpdate.Description = formData.Pizza.Description;
                    pizzaToUpdate.Price = formData.Pizza.Price;
                    pizzaToUpdate.CategoryId = formData.Pizza.CategoryId;

                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound("La pizza che volevi modificare non è stata trovata");
                }
            }

        }


        //METODO DELETE (Post)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            using (PizzaContext db = new PizzaContext())
            {
                Pizza pizzaToDelete = db.Pizzas.Where(pizza => pizza.Id == id).FirstOrDefault();

                if (pizzaToDelete != null)
                {
                    db.Pizzas.Remove(pizzaToDelete);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound("La pizza da eliminare non è stata trovata");
                }
            }
        }

    }
}

LaMiaPizzeriaConCategoriaEOrdini/Views/Pizza/Create.cshtml
@using LaMiaPizzeriaConCategoriaEOrdini

@model PizzaCategoriesView
@{
    Layout = "_LayoutPersonal";
}

<div class="container">
    <form asp-controller="Pizza" asp-action="Create" method="post">
        @Html.AntiForgeryToken()

        <div class="mb-3 form-check">
            <label>Path Immagine:</label>
            <input asp-for="Pizza.Image" type="text" class="form-control" />
            <span asp-validation-for="Pizza.Image" class="text-danger"></span>
        </div>
        <div class="mb-3 form-check">
            <label>Nome:</label>
            <input asp-for="Pizza.Name" type="text" class="form-control" />
            <span asp-validation-for="Pizza.Name" class="text-danger"></span>
        </div>
        <div class="mb-3 form-check">
            <label>Descrizione:</label>
            <textarea asp-for="Pizza.Description" rows="10" class="d-block w-100"></textarea>
            <span asp-validation-for="Pizza.Description" class="text-danger"></span>
        </div>

        <div class="mb-3 form-check">
            <label>Prezzo:</label>
            <input asp-for="Pizza.Price" type="text" class="form-control" />
            <span asp-validation-for="Pizza.Price" class="text-danger"></span>
        </div>

        <div class="mb-3 form-check">
            <label>Categoria:</label>
            <select asp-for="Pizza.CategoryId" rows="10" class="d-block w-100">
                <option value=""></option>
                @foreach (Category category in Model.Categories)
                {
                    <option value="@category.Id">@category.Title</option>
                }
            </select>
            <span asp-validation-for="Pizza.CategoryId" class="text-danger"></span>
        </div>


        <!--NOTA rispetto alle slide e live coding di Bryan ho dovuto aggiungere
            in button la proprietà formethod e specificare post, soluzione trovata su SLACK.
            Senza attraverso il debug ho notato che non mi legge HttpPost di Create'
        -->
        <div class="d-grid justify-content-end">
            <button type="submit" class="btn btn-primary btn-danger" formmethod="post">Salva</button>
        </div>

        <!-- TROVATO SU SLACK <button id="Button" type="submit" name="submit" formmethod="post" class="btn btn-secondary btn-sm btn-danger">Save</button> -->
    </form>
</div>

LaMiaPizzeriaConCategoriaEOrdini/Views/Pizza/Details.cshtml
@using LaMiaPizzeriaConCategoriaEOrdini.Models

@{
	Layout = "_LayoutPersonal";
}
@model Pizza

<div class="container">
	<div class="row">
		<div class="col-12">
			<div class="d-flex align-items-center">
				<h1 class="mt-3 mb-3">Dettagli pizza</h1>
			</div>
			<div class="post-single-image-container">
				<img src="@Model.Image" width="200">
			</div>
			<p>
				<strong>Nome:</strong>
				@Model.Name
			</p>
			<p>
				<strong>Descrizione:</strong>
				@Model.Description
			</p>
			<p>
				<strong>Prezzo</strong>
				@Model.Price
			</p>

			<!--NOTA IF AGGIUNTO IN MODO DA GESTIRE TUTTE LE PIZZE CHE NON HANNO UNA CATEGORIA
				SE NON HANNO CATEGORIA APPARE NESSUNA CATEGORIA
			-->
			<p>
				<strong>Categoria:</strong>
				@if (Model.Category is not null)
				{
					@Model.Category.Title
				}
				else
				{
					<text>Nessuna categoria</text>
				}
			</p>


		</div>
	</div>
</div>

LaMiaPizzeriaConCategoriaEOrdini/Views/Pizza/Index.cshtml
@using LaMiaPizzeriaConCategoriaEOrdini.Models

@{
	Layout = "_LayoutPersonal";
}

@model List<Pizza>



@if (Model.Count == 0)
{
	<h3>Non ci sono pizze da Visualizzare!</h3>
	<div class="d-grid justify-content-end">
		<a class="btn btn-primary btn-danger"
	   href="@Url.Action("Create", "Pizza")">
			Aggiungi pizza
		</a>
	</div>

	<div class="d-grid justify-content-end">
		<a class="btn btn-primary btn-danger"
	   href="@Url.Action("Create", "Order")">
			Ordina!
		</a>
	</div>

}
else
{


	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="d-flex justify-content-between align-items-center">
					<h1 class="mt-3 mb-3">Lista pizze</h1>
				</div>

				<div class="d-grid justify-content-end">
					<a class="btn btn-primary btn-danger"
				   href="@Url.Action("Create", "Pizza")">
						Aggiungi pizza
					</a>
				</div>

				<div class="d-grid justify-content-end">
					<a class="btn btn-primary btn-danger"
				   href="@Url.Action("Create", "Order")">
						Ordina!
					</a>
				</div>

				<table class="table post-list-table table-borderless">
					<thead>
						<tr>
							<th>ID</th>
							<th>Immagine</th>
							<th>Titolo</th>
							<th>Descrizione</th>
							<th>Prezzo</th>

						</tr>
					</thead>
					<tbody>

						@foreach (Pizza pizza in Model)
						{
							<tr>
								<td>@pizza.Id</td>
								<!-- questo è un esempio con url immagine esterna alla webapp attuale -->
								<td class="image"><img class="post-list-image" src="@pizza.Image" width="200"></td>
								<td class="title">@pizza.Name</td>
								<td class="description">@pizza.Description</td>
								<td class="price">@pizza.Price</td>

								<!-- justify-content-center  miei-buttons-post -->
								<td class="btn-group-vertical d-grid" style="height: 200px">
									<div>
										<a class="btn btn-primary btn-danger p-3" href="@Url.Action("Details", "Pizza", new { id = @pizza.Id } )" role="button">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-activity"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>
										</a>
									</div>
									<div>
										<a class="btn btn-warning btn-sm p-3" href="@Url.Action("Update", "Pizza", new { id = @pizza.Id })" role="button">
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-activity"><polygon points="14 2 18 6 7 17 3 17 3 13 14 2"></polygon><line x1="3" y1="22" x2="21" y2="22"></line></svg>
										</a>
									</div>
									<div>
										<!--NOTA PER IL TASTO DELETE SI CREA UN FINTO FORM-->
										<form asp-controller="pizza" asp-action="Delete" asp-route-id="@pizza.Id" method="post" class="d-grid">
											@Html.AntiForgeryToken()
											<button type="submit" class="btn btn-danger btn-sm p-3">
												<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-activity"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
											</button>
										</form>
									</div>
								</td>

								<!--  <td>
									  <a class="btn btn-primary" href="@@Url.Action("Details", "Post", new { id = @@pizza.Id } )" role="button">Dettagli</a>
										  </td>-->
							</tr>
						}


						<!--
						@@for(int i = 0; i < Model.Count; i++)
						{
							<tr>
								<td>@@Model[i].Id</td>

								<td class="image"><img class="post-list-image" src="@@Model[i].Image"></td>
								<td class="title">@@Model[i].Title</td>
								<td class="description">@@Model[i].Description</td>
							</tr>

						}
						-->

					</tbody>
				</table>
			</div>
		</div>
	</div>
}

LaMiaPizzeriaConCategoriaEOrdini/Views/Pizza/Update.cshtml
@model PizzaCategoriesView

<div class="container">

    <div class="d-flex align-items-center">
        <h1 class="text-danger">Modifica pizza</h1>
    </div>

    <form asp-controller="Pizza" asp-action="Update" asp-route-id ="@Model.Pizza.Id" method="post">
        @Html.AntiForgeryToken()
        <div class="mb-3">
            <label>Id:</label>
            <input asp-for="Pizza.Id" type="text" class="form-control" disabled />
        </div>
        <div class="mb-3 form-check">
            <label>Path Immagine:</label>
            <input asp-for="Pizza.Image" type="text" class="form-control" />
            <span asp-validation-for="Pizza.Image" class="text-danger"></span>
        </div>
        <div class="mb-3 form-check">
            <label>Nome:</label>
            <input asp-for="Pizza.Name" type="text" class="form-control" />
            <span asp-validation-for="Pizza.Name" class="text-danger"></span>
        </div>
        <div class="mb-3 form-check">
            <label>Descrizione:</label>
            <textarea asp-for="Pizza.Description" rows="10" class="d-block w-100"></textarea>
            <span asp-validation-for="Pizza.Description" class="text-danger"></span>
        </div>

        <div class="mb-3 form-check">
            <label>Prezzo:</label>
            <input asp-for="Pizza.Price" type="text" class="form-control" />
            <span asp-validation-for="Pizza.Price" class="text-danger"></span>
        </div>

        <div class="mb-3 form-check">
            <label>Categoria:</label>
            <select asp-for="Pizza.CategoryId" rows="10" class="d-block w-100">
                <option value=""></option> <!--Corrisponde al valore nullo per il DB-->
                @foreach (Category category in Model.Categories)
                {
                    <option value="@category.Id">@category.Title</option> 
                    <!--Corrisponde alle categorie del DB tranne valore nullo-->
                }
            </select>
            <span asp-validation-for="Pizza.CategoryId" class="text-danger"></span>
        </div>
        <!--NOTA rispetto alle slide e live coding di Bryan ho dovuto aggiungere
            in button la proprietà formethod e specificare post, soluzione trovata su SLACK.
            Senza attraverso il debug ho notato che non mi legge HttpPost di Create'
        -->
        <div class="d-grid justify-content-end">
            <button type="submit" class="btn btn-primary btn-danger" formmethod="post">Salva</button>
        </div>

        <!-- TROVATO SU SLACK <button id="Button" type="submit" name="submit" formmethod="post" class="btn btn-secondary btn-sm btn-danger">Save</button> -->
    </form>
</div>